---
- name: Ensure the application group exists
  group:
    name: "{{ nodejs_app_groupname }}"
    state: present

- name: Ensure the application user account exists
  user:
    name: "{{ nodejs_app_username }}"
    comment: "Node.js System Account"
    group: "{{ nodejs_app_groupname }}"
    shell: "{{ nodejs_app_user_shell }}"
    home: "{{ nodejs_app_home_dir }}"

- name: Clone application repository
  git:
    repo: "{{ nodejs_app_git_repo | mandatory }}"
    dest: "{{ nodejs_app_install_dir | mandatory }}"
    version: "{{ nodejs_app_git_branch | mandatory }}"
    depth: 1
  become: yes
  become_user: "{{ nodejs_app_dev_username if is_vagrant else nodejs_app_username }}"
  when: nodejs_app_git_clone

- name: Run application related commands with become if not under Docker
  command: "{{ item }}"
  args:
    chdir: "{{ nodejs_app_install_dir }}"
  with_items: "{{ nodejs_app_commands }}"
  become: yes
  become_user: "{{ nodejs_app_dev_username if is_vagrant else nodejs_app_username }}"
  when: nodejs_app_commands

- name: Set up VirtualBox Shared Folders npm workaround
  copy:
    src: npmrc
    dest: "/home/{{ nodejs_app_dev_username if nodejs_app_dev_env else nodejs_app_username }}/.npmrc"
    mode: 0644
    owner: "{{ nodejs_app_dev_username if is_vagrant else nodejs_app_username }}"
    group: "{{ nodejs_app_dev_groupname if is_vagrant else nodejs_app_groupname }}"
  when: nodejs_app_dev_env
